name: Build JAVA Application

env:
  AZURE_WEBAPP_NAME: MY_WEBAPP_NAME   # set this to your application's name
  JAVA_VERSION: '11'
  
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: checkout repo
        uses: actions/checkout@v3
      - name: check target folder before
        run: |
           pwd
           ls -lrt
      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install  
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar' 
      - name: check target folder after
        run: |
           pwd
           ls ${{ github.workspace }}/target
                      
   