name: Build JAVA Application

env:
  AZURE_WEBAPP_NAME: githubaction-greet   # set this to your application's name
  JAVA_VERSION: '11'
  
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: checkout repo
        uses: actions/checkout@v3
      - name: check target folder before
        run: |
           pwd
           ls -lrt
      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install  
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: my-app
          path: '${{ github.workspace }}/target/*.jar' 
      - name: check target folder after
        run: |
           pwd
           ls -lrt
           ls -lrt ${{ github.workspace }}/target
  
  
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'sit'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
                      
   